# -*- encoding: utf-8 -*-

=begin
#Livepeer API Reference

#Welcome to the Livepeer API reference docs. Here you will find all the endpoints exposed on the standard Livepeer API, learn how to use them and what they return. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "livepeer/version"

Gem::Specification.new do |s|
  s.name        = "livepeer"
  s.version     = livepeer::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Livepeer"]
  s.email       = [""]
  s.homepage    = "https://github.com/liveeer/livepeer-uby"
  s.summary     = "Livepeer API Reference Ruby Gem"
  s.description = "Welcome to the Livepeer API reference docs. Here you will find all the endpoints exposed on the standard Livepeer API, learn how to use them and what they return. "
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
