=begin
#Livepeer API Reference

#Welcome to the Livepeer API reference docs. Here you will find all the endpoints exposed on the standard Livepeer API, learn how to use them and what they return. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module Livepeer
  # LMPS ffmpeg profile
  class FfmpegProfile
    attr_accessor :width

    attr_accessor :name

    attr_accessor :height

    attr_accessor :bitrate

    attr_accessor :fps

    attr_accessor :fps_den

    attr_accessor :gop

    attr_accessor :profile

    attr_accessor :encoder

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'width' => :'width',
        :'name' => :'name',
        :'height' => :'height',
        :'bitrate' => :'bitrate',
        :'fps' => :'fps',
        :'fps_den' => :'fpsDen',
        :'gop' => :'gop',
        :'profile' => :'profile',
        :'encoder' => :'encoder'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'width' => :'Integer',
        :'name' => :'String',
        :'height' => :'Integer',
        :'bitrate' => :'Integer',
        :'fps' => :'Integer',
        :'fps_den' => :'Integer',
        :'gop' => :'String',
        :'profile' => :'String',
        :'encoder' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `livepeer::FfmpegProfile` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `livepeer::FfmpegProfile`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'width')
        self.width = attributes[:'width']
      else
        self.width = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'height')
        self.height = attributes[:'height']
      else
        self.height = nil
      end

      if attributes.key?(:'bitrate')
        self.bitrate = attributes[:'bitrate']
      else
        self.bitrate = nil
      end

      if attributes.key?(:'fps')
        self.fps = attributes[:'fps']
      else
        self.fps = nil
      end

      if attributes.key?(:'fps_den')
        self.fps_den = attributes[:'fps_den']
      end

      if attributes.key?(:'gop')
        self.gop = attributes[:'gop']
      end

      if attributes.key?(:'profile')
        self.profile = attributes[:'profile']
      end

      if attributes.key?(:'encoder')
        self.encoder = attributes[:'encoder']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @width.nil?
        invalid_properties.push('invalid value for "width", width cannot be nil.')
      end

      if @width < 128
        invalid_properties.push('invalid value for "width", must be greater than or equal to 128.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 500
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 500.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be great than or equal to 1.')
      end

      if @height.nil?
        invalid_properties.push('invalid value for "height", height cannot be nil.')
      end

      if @height < 128
        invalid_properties.push('invalid value for "height", must be greater than or equal to 128.')
      end

      if @bitrate.nil?
        invalid_properties.push('invalid value for "bitrate", bitrate cannot be nil.')
      end

      if @bitrate < 400
        invalid_properties.push('invalid value for "bitrate", must be greater than or equal to 400.')
      end

      if @fps.nil?
        invalid_properties.push('invalid value for "fps", fps cannot be nil.')
      end

      if @fps < 0
        invalid_properties.push('invalid value for "fps", must be greater than or equal to 0.')
      end

      if !@fps_den.nil? && @fps_den < 1
        invalid_properties.push('invalid value for "fps_den", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @width.nil?
      return false if @width < 128
      return false if @name.nil?
      return false if @name.to_s.length > 500
      return false if @name.to_s.length < 1
      return false if @height.nil?
      return false if @height < 128
      return false if @bitrate.nil?
      return false if @bitrate < 400
      return false if @fps.nil?
      return false if @fps < 0
      return false if !@fps_den.nil? && @fps_den < 1
      profile_validator = EnumAttributeValidator.new('String', ["H264Baseline", "H264Main", "H264High", "H264ConstrainedHigh"])
      return false unless profile_validator.valid?(@profile)
      encoder_validator = EnumAttributeValidator.new('String', ["h264", "hevc", "vp8", "vp9"])
      return false unless encoder_validator.valid?(@encoder)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] width Value to be assigned
    def width=(width)
      if width.nil?
        fail ArgumentError, 'width cannot be nil'
      end

      if width < 128
        fail ArgumentError, 'invalid value for "width", must be greater than or equal to 128.'
      end

      @width = width
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 500
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 500.'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be great than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] height Value to be assigned
    def height=(height)
      if height.nil?
        fail ArgumentError, 'height cannot be nil'
      end

      if height < 128
        fail ArgumentError, 'invalid value for "height", must be greater than or equal to 128.'
      end

      @height = height
    end

    # Custom attribute writer method with validation
    # @param [Object] bitrate Value to be assigned
    def bitrate=(bitrate)
      if bitrate.nil?
        fail ArgumentError, 'bitrate cannot be nil'
      end

      if bitrate < 400
        fail ArgumentError, 'invalid value for "bitrate", must be greater than or equal to 400.'
      end

      @bitrate = bitrate
    end

    # Custom attribute writer method with validation
    # @param [Object] fps Value to be assigned
    def fps=(fps)
      if fps.nil?
        fail ArgumentError, 'fps cannot be nil'
      end

      if fps < 0
        fail ArgumentError, 'invalid value for "fps", must be greater than or equal to 0.'
      end

      @fps = fps
    end

    # Custom attribute writer method with validation
    # @param [Object] fps_den Value to be assigned
    def fps_den=(fps_den)
      if fps_den.nil?
        fail ArgumentError, 'fps_den cannot be nil'
      end

      if fps_den < 1
        fail ArgumentError, 'invalid value for "fps_den", must be greater than or equal to 1.'
      end

      @fps_den = fps_den
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] profile Object to be assigned
    def profile=(profile)
      validator = EnumAttributeValidator.new('String', ["H264Baseline", "H264Main", "H264High", "H264ConstrainedHigh"])
      unless validator.valid?(profile)
        fail ArgumentError, "invalid value for \"profile\", must be one of #{validator.allowable_values}."
      end
      @profile = profile
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] encoder Object to be assigned
    def encoder=(encoder)
      validator = EnumAttributeValidator.new('String', ["h264", "hevc", "vp8", "vp9"])
      unless validator.valid?(encoder)
        fail ArgumentError, "invalid value for \"encoder\", must be one of #{validator.allowable_values}."
      end
      @encoder = encoder
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          width == o.width &&
          name == o.name &&
          height == o.height &&
          bitrate == o.bitrate &&
          fps == o.fps &&
          fps_den == o.fps_den &&
          gop == o.gop &&
          profile == o.profile &&
          encoder == o.encoder
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [width, name, height, bitrate, fps, fps_den, gop, profile, encoder].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Livepeer.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
