=begin
#Livepeer API Reference

#Welcome to the Livepeer API reference docs. Here you will find all the endpoints exposed on the standard Livepeer API, learn how to use them and what they return. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module livepeer
  class Session
    attr_accessor :id

    attr_accessor :name

    attr_accessor :last_seen

    attr_accessor :source_segments

    attr_accessor :transcoded_segments

    # Duration of all the source segments, sec
    attr_accessor :source_segments_duration

    # Duration of all the transcoded segments, sec
    attr_accessor :transcoded_segments_duration

    attr_accessor :source_bytes

    attr_accessor :transcoded_bytes

    # Rate at which sourceBytes increases (bytes/second)
    attr_accessor :ingest_rate

    # Rate at which transcodedBytes increases (bytes/second)
    attr_accessor :outgoing_rate

    attr_accessor :is_healthy

    attr_accessor :issues

    # Timestamp (in milliseconds) at which the stream object was created
    attr_accessor :created_at

    # Points to the parent stream object
    attr_accessor :parent_id

    # Should this stream be recorded? Uses default settings. For more customization, create and configure an object store. 
    attr_accessor :record

    # Status of the recording process of this stream session.
    attr_accessor :recording_status

    # URL for accessing the recording of this stream session.
    attr_accessor :recording_url

    # URL for the stream session recording packaged in an mp4.
    attr_accessor :mp4_url

    # Used to form the playback URL
    attr_accessor :playback_id

    attr_accessor :profiles

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'last_seen' => :'lastSeen',
        :'source_segments' => :'sourceSegments',
        :'transcoded_segments' => :'transcodedSegments',
        :'source_segments_duration' => :'sourceSegmentsDuration',
        :'transcoded_segments_duration' => :'transcodedSegmentsDuration',
        :'source_bytes' => :'sourceBytes',
        :'transcoded_bytes' => :'transcodedBytes',
        :'ingest_rate' => :'ingestRate',
        :'outgoing_rate' => :'outgoingRate',
        :'is_healthy' => :'isHealthy',
        :'issues' => :'issues',
        :'created_at' => :'createdAt',
        :'parent_id' => :'parentId',
        :'record' => :'record',
        :'recording_status' => :'recordingStatus',
        :'recording_url' => :'recordingUrl',
        :'mp4_url' => :'mp4Url',
        :'playback_id' => :'playbackId',
        :'profiles' => :'profiles'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'last_seen' => :'Float',
        :'source_segments' => :'Float',
        :'transcoded_segments' => :'Float',
        :'source_segments_duration' => :'Float',
        :'transcoded_segments_duration' => :'Float',
        :'source_bytes' => :'Float',
        :'transcoded_bytes' => :'Float',
        :'ingest_rate' => :'Float',
        :'outgoing_rate' => :'Float',
        :'is_healthy' => :'IsHealthy',
        :'issues' => :'HumanIssues',
        :'created_at' => :'Float',
        :'parent_id' => :'String',
        :'record' => :'Boolean',
        :'recording_status' => :'String',
        :'recording_url' => :'String',
        :'mp4_url' => :'String',
        :'playback_id' => :'String',
        :'profiles' => :'Array<FfmpegProfile>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `livepeer::Session` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `livepeer::Session`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'last_seen')
        self.last_seen = attributes[:'last_seen']
      end

      if attributes.key?(:'source_segments')
        self.source_segments = attributes[:'source_segments']
      end

      if attributes.key?(:'transcoded_segments')
        self.transcoded_segments = attributes[:'transcoded_segments']
      end

      if attributes.key?(:'source_segments_duration')
        self.source_segments_duration = attributes[:'source_segments_duration']
      end

      if attributes.key?(:'transcoded_segments_duration')
        self.transcoded_segments_duration = attributes[:'transcoded_segments_duration']
      end

      if attributes.key?(:'source_bytes')
        self.source_bytes = attributes[:'source_bytes']
      end

      if attributes.key?(:'transcoded_bytes')
        self.transcoded_bytes = attributes[:'transcoded_bytes']
      end

      if attributes.key?(:'ingest_rate')
        self.ingest_rate = attributes[:'ingest_rate']
      end

      if attributes.key?(:'outgoing_rate')
        self.outgoing_rate = attributes[:'outgoing_rate']
      end

      if attributes.key?(:'is_healthy')
        self.is_healthy = attributes[:'is_healthy']
      end

      if attributes.key?(:'issues')
        self.issues = attributes[:'issues']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'parent_id')
        self.parent_id = attributes[:'parent_id']
      end

      if attributes.key?(:'record')
        self.record = attributes[:'record']
      end

      if attributes.key?(:'recording_status')
        self.recording_status = attributes[:'recording_status']
      end

      if attributes.key?(:'recording_url')
        self.recording_url = attributes[:'recording_url']
      end

      if attributes.key?(:'mp4_url')
        self.mp4_url = attributes[:'mp4_url']
      end

      if attributes.key?(:'playback_id')
        self.playback_id = attributes[:'playback_id']
      end

      if attributes.key?(:'profiles')
        if (value = attributes[:'profiles']).is_a?(Array)
          self.profiles = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      recording_status_validator = EnumAttributeValidator.new('String', ["waiting", "ready", "none"])
      return false unless recording_status_validator.valid?(@recording_status)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] recording_status Object to be assigned
    def recording_status=(recording_status)
      validator = EnumAttributeValidator.new('String', ["waiting", "ready", "none"])
      unless validator.valid?(recording_status)
        fail ArgumentError, "invalid value for \"recording_status\", must be one of #{validator.allowable_values}."
      end
      @recording_status = recording_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          last_seen == o.last_seen &&
          source_segments == o.source_segments &&
          transcoded_segments == o.transcoded_segments &&
          source_segments_duration == o.source_segments_duration &&
          transcoded_segments_duration == o.transcoded_segments_duration &&
          source_bytes == o.source_bytes &&
          transcoded_bytes == o.transcoded_bytes &&
          ingest_rate == o.ingest_rate &&
          outgoing_rate == o.outgoing_rate &&
          is_healthy == o.is_healthy &&
          issues == o.issues &&
          created_at == o.created_at &&
          parent_id == o.parent_id &&
          record == o.record &&
          recording_status == o.recording_status &&
          recording_url == o.recording_url &&
          mp4_url == o.mp4_url &&
          playback_id == o.playback_id &&
          profiles == o.profiles
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, last_seen, source_segments, transcoded_segments, source_segments_duration, transcoded_segments_duration, source_bytes, transcoded_bytes, ingest_rate, outgoing_rate, is_healthy, issues, created_at, parent_id, record, recording_status, recording_url, mp4_url, playback_id, profiles].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = livepeer.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
