=begin
#Livepeer API Reference

#Welcome to the Livepeer API reference docs. Here you will find all the endpoints exposed on the standard Livepeer API, learn how to use them and what they return. 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for livepeer::RequestUpload200ResponseTask
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe livepeer::RequestUpload200ResponseTask do
  let(:instance) { livepeer::RequestUpload200ResponseTask.new }

  describe 'test an instance of RequestUpload200ResponseTask' do
    it 'should create an instance of RequestUpload200ResponseTask' do
      expect(instance).to be_instance_of(livepeer::RequestUpload200ResponseTask)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
